name: CI - staging

on:
  push:
    branches:
      - staging

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: yarn policies set-version 1.22.4
      - run: yarn install --frozen-lockfile
      - run: sudo yarn run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
